### ISSUE TITLE
list of dependencies to use jvm-toxcore-c

### ISSUE THREAD

**Issue by zoff99** [TokTok/jvm-toxcore-c#11]
with android studio i used it and compiled antox. it compiles without error.
but on runtime crashes with class not found.
seems it needs some specific dependencies installed (with specific version), but you can not see it anywhere.

is there a list what libs are needed as dependencies for jvm-toxcore-c?

**Comment by zoff99** [comment]
as there is no source code for the proto stuff, you can not look at the source for dependencies.
so i decompiled the finished antox.apk and looked at the class source to find the import statements.

**Comment by iphydf** [comment]
Fixed in #12, depending on the jvm-sbt-plugins PR.
