### ISSUE TITLE
[WIP] c-toxcore reference implementation for Android

### ISSUE THREAD

**Issue by zoff99** [TokTok/jvm-toxcore-c#27]
https://github.com/zoff99/ToxAndroidRefImpl/tree/master/jni-c-toxcore

**not 100% complete yet**, but most stuff is working.

see the "test client" development snapshot that's using it:
https://circleci.com/api/v1/project/zoff99/ToxAndroidRefImpl/latest/artifacts/0/$CIRCLE_ARTIFACTS/ToxAndroidRefImpl.apk?filter=successful&branch=master

**!! Use at your own risk !!**

**Comment by iphydf** [comment]
Can you send a PR to add a link to that to our readme? So people know there is an alternative.

**Comment by iphydf** [comment]
No action here.
