### ISSUE TITLE
failed to build i686-linux-android 

### ISSUE THREAD

**Issue by 1971192997** [TokTok/jvm-toxcore-c#68]
following is the log hope for you help...thanks
/home/ubuntu/toxapp/jvm-toxcore-c/_build/i686-linux-android/protobuf/src/.libs/libprotobuf.a(arena.o):/home/ubuntu/toxapp/jvm-toxcore-c/_git/protobuf/src/google/protobuf/arena.cc:function google::protobuf::internal::ArenaImpl::Init(): error: undefined reference to '__atomic_fetch_add_8'

clang38++: error: linker command failed with exit code 1 (use -v to see invocation)

make[3]: *** [protoc] Error 1

make[3]: Leaving directory `/home/ubuntu/toxapp/jvm-toxcore-c/_build/i686-linux-android/protobuf/src'

make[2]: *** [install-recursive] Error 1

**Comment by zoff99** [comment]
@1971192997 can you explain what you want to do?
are you trying to compile Antox from scratch? what is your goal?

**Comment by 1971192997** [comment]
@zoff99 
i am trying to build "x86/libtox4j-c.so"
here is my steps:
Makefile
 1$(MAKE) -f scripts/build-host
2(MAKE) -f scripts/build-i686-linux-android

and then make error

**Comment by zoff99** [comment]
yes, but why? what do you want to do with this library? what application do you want to run?

**Comment by 1971192997** [comment]
i am trying to compile Antox with libtox4j-c.so on i686-linux-android

**Comment by zoff99** [comment]
maybe you want to try TRIfA first?
https://github.com/zoff99/ToxAndroidRefImpl

**Comment by 1971192997** [comment]
got it, thanks
