### ISSUE TITLE
Usage example / documentation

### ISSUE THREAD

**Issue by F0x06** [TokTok/jvm-toxcore-c#7]
Hi !

First thank you for the project, i have troubles making a working application using Tox4J, where i can find documentation ? An "EchoBot" example would be perfect ! :)

Thank you.

**Comment by iphydf** [comment]
An echo bot example would indeed be useful. I'll make one when I get around to it. In the meantime, a more comprehensive example would be the test GUI: https://github.com/TokTok/jvm-toxcore-c/tree/master/src/test/java/im/tox/gui. It might make sense to rip it out of the jvm-toxcore-c repo and make a new one for it. That would only make sense if someone is going to develop it, though (perhaps you? :)).

**Comment by iphydf** [comment]
Done: https://github.com/TokTok/echobot-jvm
And for a larger example: https://github.com/TokTok/jtox
